### ISSUE TITLE
Trouble comipiling (dependency problem)

### ISSUE THREAD

**Issue by iaraknes** [jamesward/play2bars#1]
I had some trouble with Jquery, when trying to run the application the first time.
I solved it by replacing a line in Build.scala:
-      "com.jquery" % "jquery" % "1.7.1"
-      "com.jquery" % "jquery" % "1.7.1" from "http://code.jquery.com/jquery-1.7.1.min.js"

**Comment by iaraknes** [comment]
I may add that it happened on the "scala-squeryl"-branch.

**Comment by jamesward** [comment]
Sorry about that.  I forgot to add the webjars resolver:  
https://github.com/jamesward/play2bars/commit/e3a1f7cb681471866b3cf8ee893d6b33964fbc85
