### ISSUE TITLE
Stuck trying to run it for the 1st time

### ISSUE THREAD

**Issue by rodolfo42** [jamesward/play2bars#5]
Hi,

So, all I did was to clone the project and switch to the branch `scala-squeryl`. I tried to run it with `play` but got many errors as follows.

```
$ play --version
sbt launcher version 0.13.0
```
## 1st error

When I typed `play`, at first it didn't recognize the sbt version. I got this:

```
$ play
Getting org.scala-sbt sbt 0.11.3 ...

:: problems summary ::
:::: WARNINGS
        module not found: org.scala-sbt#sbt;0.11.3

    ==== local: tried

      /usr/local/Cellar/play/2.2.2/libexec/repository/local/org.scala-sbt/sbt/0.11.3/ivys/ivy.xml
```

Then I updated the `project/build.properties` file to the version I was using:

```
sbt.version=0.13.0
```
## 2nd error

Then I ran `play` again and this time I got:

```
sbt.ResolveException: unresolved dependency: play#sbt-plugin;2.0.4: not found
```

So I went to `project/plugins.sbt` and changed the sbt plugin version to the following, as I saw [here](http://www.playframework.com/documentation/2.0/Build):

```
addSbtPlugin("play" % "sbt-plugin" % "2.0")
```
## 3rd error

Ran `play` again. And then I got:

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: play#sbt-plugin;2.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]      play:sbt-plugin:2.0 (sbtVersion=0.13, scalaVersion=2.10)
[warn] 
sbt.ResolveException: unresolved dependency: play#sbt-plugin;2.0: not found
```

Then I read [here](http://www.playframework.com/documentation/2.1.x/Migration) that I would need to set the sbt-plugin version to `2.1.0`. So I did.
## 4th error

After running `play` I got another one:

```
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]      play:sbt-plugin:2.1.0 (sbtVersion=0.13, scalaVersion=2.10)
[warn] 
sbt.ResolveException: unresolved dependency: play#sbt-plugin;2.1.0: not found
```

I really like the Play project and spiked it a few times already. Could you point me in the right direction regarding those versioning issues? I could update and test them, then send a PR correcting it.

This kind of thing makes it very difficult for newcomers to adopt Play.. I'm actually investing some of my time trying to make other adopt it, and also Scala in general.

Thanks!

**Comment by rodolfo42** [comment]
Also, I read something [here](http://www.playframework.com/documentation/2.1.x/Migration) again, so I tried just now to update the sbt version again to:

```
sbt.version=0.12.2
```

But I got:

```
    [SUCCESSFUL ] org.scala-sbt#test-agent;0.12.2!test-agent.jar (827ms)
:: retrieving :: org.scala-sbt#boot-app
    confs: [default]
    40 artifacts copied, 0 already retrieved (8381kB/50ms)
java.lang.NoSuchMethodError: scala.Predef$.augmentString(Ljava/lang/String;)Lscala/collection/immutable/StringOps;
```

**Comment by jamesward** [comment]
This stuff is definitely out-of-date.  Sorry.  The problems you encountered all seem to be because you are using a different version of Play and this app uses.

Instead of messing with this old sample, check out a new Activator template I created from this code:
https://typesafe.com/activator/template/play2bars-squeryl

That should provide a much easier way to get up and running.  Let me know on the new project if you have any issues: https://github.com/jamesward/play2bars-squeryl

**Comment by rodolfo42** [comment]
Nice, thanks for the attention

Got the new template up and running just fine now, thanks
